export const CREATE_ORDER_SERVICE = Symbol('CREATE_ORDER_SERVICE');
export const GET_ORDER_SERVICE = Symbol('GET_ORDER_SERVICE');
export const LIST_PROCESSING_ORDER_SERVICE = Symbol('LIST_PROCESSING_ORDER_SERVICE');